Homepage TNW clone Responsive design
karthi07/Responsive-design pull request #1
Opened 2020-03-19 14:05 UTC by karthi07

## Responsive design project

We have implemented  the homepage on thenextweb.com in responsive layout

We used
 -  Media queries for width size 768, 1024 and greater
 -  Grid Layout,
 -  Flex Layout,
 -  absolute positioning

2020-03-19 14:51 UTC, karthi07 commented
Stickler activated for the repo after creating the pull request, hence its check arent visible.

 - the project has no stickler errors [ can check at the last commit info ]

P.S: In case I can create the new pull request if required. [ if required please comment before the review ]

2020-03-19 20:56 UTC, majovanilla requested changes
Hey team, 👋

## Good job on this project! 👍


- Good Readme file
- Good Pull Request Message

There are still some changes 👇 you need to implement to approve this request 🔍

### Required Changes: ✍️

- [x] The general width of the content of the page is slightly different from the original one (all except for the top three articles and the navbar). That makes the articles to appear wider and more separate than they should be. Please fix this.

- [x] Your CSS file could be better organized: 
     - When you have repetitive properties in different classes, you can put them together. 
     - You have your media queries all over your file. They should be at the end of it, and not be repeated.
        This means you need to put all the classes together in the right media query size and have only one
        per size.

- [x] Read the rest of the changes below and work on all of them, please.

### Optional Changes:

If you want to make your project even better 🔥💥, I have a few suggestions you can implement.  

These are completely [Optional]: 🦔

- I left some options changes in the comments below. 

If you have any questions, feel free to send me a message through Slack (@majo)
I would be happy to help! 👩‍💻 


Happy coding 🤓

--Maria Reyes

2020-03-19 20:56 UTC, majovanilla commented on README.md
> +
- [ ] Improve your Readme file. It should be descriptive of the project. You are using the correct template but now you need to fill it with information about your project. You can add details about what you did in this project, why you did it, how you did it...Check this [link](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/) for more info.

2020-03-19 20:56 UTC, majovanilla commented on index.html
> +    <ul>
- [ ] The tablet version should show the TNW logo. In your page it's only displayed in the mobile version.

2020-03-19 20:56 UTC, majovanilla commented on index.html
> +      <article class="article art-1">
- [ ] The images in the art-ctn section are not displaying correctly in the mobile version. They should have a larger height.
![Screenshot from 2020-03-19 11-54-51](https://user-images.githubusercontent.com/51926937/77099141-14712300-69d9-11ea-9fc4-7e6f926ccf1c.png)

Original:
![Screenshot from 2020-03-19 11-54-56](https://user-images.githubusercontent.com/51926937/77099151-1804aa00-69d9-11ea-802c-2626dac9fab7.png)

2020-03-19 20:56 UTC, majovanilla commented on index.html
> +    <div class="art-ctn">
- [ ] You should use the `section` tag on this case. See the use of [semantic HTML](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/semantic_html_requirement.png) in the requirements of the project.

2020-03-19 20:56 UTC, majovanilla commented on index.html
> +      </div>
- [ ] The articles in the desktop version are too separated. Please check the images below and make sure you make the necessary changes.
This happens with the rest of the sections of the page (except the first 3 images) because you have a different width.

![Screenshot from 2020-03-19 12-34-20](https://user-images.githubusercontent.com/51926937/77102257-2903ea00-69de-11ea-905d-2743fab97680.png)

Original:
![Screenshot from 2020-03-19 12-34-26](https://user-images.githubusercontent.com/51926937/77102272-2dc89e00-69de-11ea-9a40-3f91011170f0.png)

In the mobile version, the images are disproportioned. Please fix them.
![Screenshot from 2020-03-19 12-37-56](https://user-images.githubusercontent.com/51926937/77102499-8bf58100-69de-11ea-8ab5-7a1e5746901c.png)

2020-03-19 20:56 UTC, majovanilla commented on index.html
> +          <li class="br-line">|</li>
- [ ] The articles in this section should be three when you are in the tablet version. Your page is showing 4.
![Screenshot from 2020-03-19 13-07-08](https://user-images.githubusercontent.com/51926937/77105084-ad586c00-69e2-11ea-92e5-a7a419e47716.png)

- [ ] The same case happens in the mobile version. Please make the necessary adjustments.

2020-03-19 20:56 UTC, majovanilla commented on index.html
> +          <li>See more</li>
- [ ] The font-size of the menu should be smaller in the mobile version.

2020-03-19 20:56 UTC, majovanilla commented on index.html
> +            <div class="sec-text-title">
- [ ] The font-size here is affecting the way the title displays. Check the images below and make the necessary adjustments.
![Screenshot from 2020-03-19 13-10-08](https://user-images.githubusercontent.com/51926937/77105316-17711100-69e3-11ea-8967-dc58bbd5247c.png)

Original:
![Screenshot from 2020-03-19 13-10-13](https://user-images.githubusercontent.com/51926937/77105325-1b049800-69e3-11ea-924f-75d41997e615.png)

2020-03-19 20:56 UTC, majovanilla commented on index.html
> +              <li class="sec-text-li"> <a href="#">  Instagram will place coronavirus advice front and center on your feed </a></li>
- [ ] Check the font-size of these elements, too and make it look like the original page (it could also be the font-family you are using)

- [ ] Check the padding. The bullet points look cramped.

2020-03-19 20:56 UTC, majovanilla commented on index.html
> +          <h2>Apps ></h2>
- [ ] All the categories in this section should have a larger article image when you are in the mobile version. See:
![Screenshot from 2020-03-19 13-12-59](https://user-images.githubusercontent.com/51926937/77105653-9b2afd80-69e3-11ea-9f3f-1b0b17148b52.png)

Original:
![Screenshot from 2020-03-19 13-13-06](https://user-images.githubusercontent.com/51926937/77105663-9f571b00-69e3-11ea-9dc9-7619110c24ca.png)

2020-03-19 20:56 UTC, majovanilla commented on index.html
> +          </ul>
- [ ] These elements should be links, like the original page.

2020-03-19 20:56 UTC, majovanilla commented on index.html
> +    <div class="ft-ctn">
- [ ] You are using a brown background color for this part. Please adjust it to be like the original page.

2020-03-19 20:56 UTC, majovanilla commented on style.css
> +  /* font-family: 'Cantata One', serif; */
- [ ] Please delete commented code.

2020-03-19 20:56 UTC, majovanilla commented on style.css
> +  /* border: 1px solid white; */
- [ ] Please delete commented code.

2020-03-19 20:56 UTC, majovanilla commented on style.css
> +}
- [ ] Avoid repetition of classes, you could put this one together with the `btm-cnt a` class, since they have the same properties.

2020-03-19 20:56 UTC, majovanilla commented on style.css
> +  background-position: center;
- [ ] **optional** Have you tried the background shorthand? It's really useful. You could do it like this:
`background:  url(images/search.png) no-repeat center `

2020-03-19 20:56 UTC, majovanilla commented on style.css
> +  background-position: center;
- [ ] Try the shorthand here!

2020-03-19 20:56 UTC, majovanilla commented on style.css
> +  background-position: center;
- [ ] And here!

2020-03-19 20:56 UTC, majovanilla commented on style.css
> +
- [ ] Please put these two classes together to avoid repetition.

2020-03-19 20:56 UTC, majovanilla commented on style.css
> +  background-size: 100% 100%;
- [ ] Try the background shorthand here.

2020-03-19 20:56 UTC, majovanilla commented on style.css
> +  background-size: cover;
- [ ] And here!

2020-03-19 20:56 UTC, majovanilla commented on style.css
> +  }
- [ ] Put these three classes together to avoid repetition.

2020-03-19 20:56 UTC, majovanilla commented on style.css
> +}
- [ ] This is the best way to avoid repetition!

2020-03-20 06:13 UTC, karthi07 commented on index.html
> +      <article class="article art-1">
fixed

2020-03-20 09:07 UTC, karthi07 commented
we have fixed the required changes and almost all the optional changes.

2020-03-20 09:57 UTC, lekegitrepo commented
### Hi Team 👏 👏 
### You have fixed most of the required changes but some are still not implemented. According to the previous reviewer, you need to:

**_1. Make the images in the art-ctn section display correctly in the mobile version. They should have a larger height._**  **_"The images in the art-ctn section are not displaying correctly in the mobile version. They should have a larger height."_**

**_2. Change the footer color: "You are using a brown background color for this part. Please adjust it to be like the original page."_**

**_3. The logo is missing: screen size 1024px_**

![image](https://user-images.githubusercontent.com/48312803/77152395-8428f180-6a5d-11ea-9e06-a3f1a004bc37.png)

**_Kindly, make these changes and submit for review._**

**_If you have any doubt or question contact me on slack._**

### _Reviewed by: Temitayo Adeleke_

2020-03-20 09:58 UTC, lekegitrepo requested changes
### Status: Require changes

2020-03-20 11:05 UTC, karthi07 commented
Completed the required changes.

https://rawcdn.githack.com/karthi07/Responsive-design/a824292aa5ae482834fe6e7a80ee90e0e4d28e82/index.html

2020-03-20 11:18 UTC, lekegitrepo commented
> Completed the required changes.
> 
> https://rawcdn.githack.com/karthi07/Responsive-design/a824292aa5ae482834fe6e7a80ee90e0e4d28e82/index.html

Hi

2020-03-20 12:40 UTC, lekegitrepo commented
### Well done 🥇 🥇 💯 💯 
### This page looks great now and good job for implementing the required changes. This project is approved.

### Reviewed by: Temitayo Adeleke

-   Github: [@lekegitrepo](https://github.com/lekegitrepo)
-   Twitter: [@leketemi](https://twitter.com/leketemi)
-   Linkedin: [linkedin](https://www.linkedin.com/in/adeleke-temitayo-a69125188/)

2020-03-20 12:41 UTC, lekegitrepo approved these changes
### Status: Approved

2020-03-20 12:44 UTC, merged